
name: Test & Build

on:
  push:
    branches: [ "main", "ft/user_registration" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: backend-desapp-api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: permissions
        run: chmod +x gradlew
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: '17'

      - name: Read .env file
        id: dotenv
        run: |
          echo "Reading .env file"
          set -a
          . .env
          set +a
          echo "Some api env: $SPRING_APPLICATION_NAME"
          echo "Binance api env: $INTEGRATION_BINANCE_API_URL"
        working-directory: ${{ github.workspace }}

      - name: Check dependencies
        run: ./gradlew dependencies
      - name: Set up proxy
        run: |
          export HTTP_PROXY=http://35.185.196.38:3128
          export HTTPS_PROXY=https://35.185.196.38:3128
      - name: Check Binance API connectivity
        run: |
          echo "Checking Binance API connectivity..."
          curl -v "https://api1.binance.com/api/v3/ticker/price?symbol=BTCUSDT"

      - name: Build with Gradle
        run: |
          export INTEGRATION_BINANCE_API_URL="https://api1.binance.com/api/v3/"
          echo "Binance api env: $INTEGRATION_BINANCE_API_URL"
          ./gradlew build --no-daemon

  tests:
    needs: build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: backend-desapp-api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: permissions
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Read .env file
        id: dotenv
        run: |
          echo "Reading .env file"
          set -a
          . .env
          set +a
        working-directory: ${{ github.workspace }}

      - name: Binance connectivity test
        run: curl -v https://api1.binance.com/api/v3/

      - name: Run tests
        run: ./gradlew test --no-daemon

